[Model monitoring] Add ModelMonitoringProject schema + functionality. (#6757)
* add ModelMonitoringMetadata

* rename the table

* add migration file

* added a new delete while removing a project.

* add migrations file

* change migration file
add store function without a connection to the code...

* add store_model_monitoring_project in deployment.py

* remove line

* add store_model_monitoring_project

* need to continue _transform_model_monitoring_project_to_schema

* created test for debugging test_model_monitoring_project

* remove table

* add add_model_monitoring_project_table

* lint

* add remove model_monitor_project also when disabling model monitor on a project.

finished db test:)

* add model_monitoring_project to test_projects.py.

* added tzdata to requirements in order to solve:
ZoneInfoNotFoundError: 'No time zone found with key utc'

* remove model_monitoring_project usage from crud.

we want to use it at this time only in db-level.

* fix log

* added update_model_monitoring_project + test.

* remove tzdata

* add "updated" field to ModelMonitoringProject

* lint

* add updated field to test + fixes.